// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gritwrrbcuosjntzgozx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyaXR3cnJiY3Vvc2pudHpnb3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NjI0MzIsImV4cCI6MjA1ODQzODQzMn0.79Q6Hn3hRkQT2o9G2-LaexLHf4JRfmfpbrbyP6xkYbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);